spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

#logging:
#  level:
#    am.itspace.order_service: trace
#    root: info
#  file:
#    name: logs/${spring.application.name}.log
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 7
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ecom_order_service_db
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#
#
#server:
#  port: 8083