spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sample:
      probability: 1.0

server:
  port: 8888
